### ISSUE TITLE
LOG_QUERIES=true only logs for 9/18 connection.query lines

### ISSUE THREAD

**Issue by avimar** [balderdashy/sails-mysql#173]
When running with LOG_QUERIES=true I didn't see some mysql queries.
I checked adapter.js and I see 18 connection.query calls, but only 9 LOG_QUERIES checks.

Thanks!

**Comment by eddieajau** [comment]
So, I'd like to help solve this but I'd need a little direction on the preferred _Sails Way_ to do it.

First off, I think you should be able to override `LOG_QUERIES` in the connection configuration.

Second, I think we need to replace all the `console.log`-ing with a `log` method internal to the module.

Third and "somehow" we need to be able to inject a logger in there to decouple logging from `console.log`. That will be a little tricky because you can't just do:

```js
logger: sails.log
```

in `connections.js` because `sails` doesn't exist yet. So maybe there's a `setLogger` mechanism?

Thanks in advance.

**Comment by devinivy** [comment]
If this becomes configurable, we need to let sails deal with certain issues on its own–for example the disconnect between when `sails` exists and when the configuration options are set.  Sails could, for example, take a string option there and transform it into the sails logger just-in-time.  I just want to make sure that waterline/adapter design decisions aren't overly impacted by the structure of sails, given that sails and waterline are decoupled for a reason.

I like your ideas here.  Robust logging mechanisms should definitely be on the roadmap for waterline and the adapters.  For now, I think a good first step would be to replace `console.log` with a configurable logger (internal to sails-mysql) that can be turned off and on with the existing `LOG_QUERIES` environment variable, since that's a fairly straightforward task.  The next step could be to add configuration options to the connection to deal with logging.

**Comment by avimar** [comment]
I've been using restify with bunyan for logging (waterline alone, not sails). The ability to to pass in a bunyan logger, or even better -  a distinct logger per query (with the request ID embedded) would seemingly be ideal.

**Comment by eddieajau** [comment]
Is there a style guide for code formatting?

**Comment by eddieajau** [comment]
PR #211 submitted for review.

**Comment by avimar** [comment]
Awesome!
