### ISSUE TITLE
SSH Connection

### ISSUE THREAD

**Issue by jasonhejna** [balderdashy/sails-mysql#194]
Is there any way to use sails-mysql to do an ssh connection to a remote sql db?

**Comment by tjwebb** [comment]
Do most MySQL drivers support connecting to the database over SSH? I've never heard of anyone doing this.

If you mean SSL and not SSH, then yes, that's supported.

**Comment by jasonhejna** [comment]
We use it mostly for working with databases while running code locally.
MySQL pro has it. Dunno, the IT manager at my company probably loves SSH a
little too much.

**Comment by tjwebb** [comment]
Yea, tunneling a database connection through SSH is kind of silly; you can achieve better security using SSL, and you don't have to rely on any specialness to make that work. Maybe someone who knows MySQL better than I can speak to this, but as a general concept, it doesn't make a lot of sense to me.

If you find out otherwise please update us. Thanks

**Comment by brandonsimpson** [comment]
Tunneling a db connection isn't silly, it's security. Having outside access to mysql ports shut off without proper server access rights keeps the mysql server more secure from outside hacks on open ports. That being said, I've never seen anything other than a mysql gui having ssh tunneling capabilities. You wouldn't do this with code, because each db connection would be expensive and slow. You'd probably want to open the mysql port access on the firewall to your specific ip address that needs to connect to the server. For all other connections they would still need ssh access.

**Comment by tjwebb** [comment]
> Tunneling a db connection isn't silly, it's security. Having outside access to mysql ports shut off without proper server access rights keeps the mysql server more secure from outside hacks on open ports.

You're saying that opening the SSH port is more secure than opening database port? Best practices typically have the SSH port closed to the world unless it's absolutely necessary. Now you're exposing your entire machine -- including the database -- to SSH attacks. If **security** is your goal, that makes no sense.

**Comment by brandonsimpson** [comment]
No, I'm saying you would open access to the mysql port to the one user's ip address only, giving them remote access to the database without tunneling through ssh. That's what he was asking about.

Regarding ssh security, you don't have to shut it off completely to be secure. You can lock the servers down via the firewall as well to only allow the ssh port to certain ip's or ip ranges (or within an office ip range via vpn), and setup public/private key pairs for those who need access and shut off root ssh access by default. You can also rate limit the connections and change the ssh default port as well to cut down on brute force attacks, but locking the ssh access down to only be accessed by non-root users with private keys is plenty secure. Sure, not as secure as completely being turned off, but for those of us who have to remotely manage linux servers, turning off ssh completely isn't an option.
