### ISSUE TITLE
.populate() only populate the first record

### ISSUE THREAD

**Issue by zeluis9** [balderdashy/sails-mysql#292]
Hi there guys. I think I've found a bug on `.populate()`;
When using

```javascript
myModel.find(myWhereClause).populate('field_a').populate('field_b')
```
the returned values are something like

```javascript
[{ field_a: 
   { foo: 'bar' },
  field_b: 
   { foo: 'bar' },
  a_number: '1405849',
  a_date: '2014-10-01T23:00:00.000Z' },
{ field_a: {},
  field_b: {},
  a_number: '1405837',
  a_date: '2014-09-30T23:00:00.000Z' },
{ field_a: {},
  field_b: {},
  a_number: '1405812',
  a_date: '2014-09-30T23:00:00.000Z' },
{ field_a: {},
  field_b: {},
  a_number: '1405842',
  a_date: '2014-10-01T23:00:00.000Z' },
{ field_a: {},
  field_b: {},
  a_number: '1405866',
  a_date: '2014-10-01T23:00:00.000Z' },
{ field_a: {},
  field_b: {},
  a_number: '1405874',
  a_date: '2014-10-01T23:00:00.000Z' },
{ field_a: {},
  field_b: {},
  a_number: '1405877',
  a_date: '2014-10-01T23:00:00.000Z' },
{ field_a: {},
  field_b: {},
  a_number: '1405879',
  a_date: '2014-10-02T23:00:00.000Z' },
{ field_a: {},
  field_b: {},
  a_number: '1405880',
  a_date: '2014-10-02T23:00:00.000Z' },
{ field_a: {},
  field_b: {},
  a_number: '1405904',
  a_date: '2014-10-03T23:00:00.000Z' }]
```
I am sure that all the records have an association defined correctly.

My where clause is something like 
```javascript
{
  where: {or:[{field_c: {"contains": mParam}}, {field_d: {"contains": mParam2}}]}, 
  select: ["field_a", "field_b", "a_number", "a_date"],
  skip: 0,
  limit: 10,
  sort: 'id ASC'  
}
```

**NodeJS Version:** 4.3.2
**Sails.JS Version:** 0.11.5
**Sails-mysql Version:** 0.11.5
**OS:** Ubuntu 14.04.4 LTS

If I'm missing something, please accept my humble apologies.

**Comment by zeluis9** [comment]
I found the problem. You have to return the `id` field for this to work.
@devinivy is this the way that is intended to work? I'm still sure this is a bug.

**Comment by particlebanana** [comment]
@zeluis9 `select` isn't supported in Waterline. There is a [proposal](https://github.com/balderdashy/waterline/pull/1310) for it in the works that indeed handles primary and foreign keys correctly.

**Comment by zeluis9** [comment]
Hi @particlebanana. By 'not supported' you mean that the current implementation is broken or buggy right? I'm sure that i've read that somewhere on the docs. Help needed?

**Comment by particlebanana** [comment]
The only reference I found was [here](https://github.com/balderdashy/waterline-docs/blob/master/queries/query-language.md#select) which I didn't add and is certainly not tested anywhere or supported. Looks like we should remove that.

**Comment by mikermcneil** [comment]
@zeluis9 as @particlebanana mentioned, physical-layer projections are not supported in the currently released version of Waterline.  Today, you have to use lower-level queries if you need them.

We're working on this for the next release of waterline-- based largely on the great work the guys at Postman have done over in [sails-mysql-transactions](https://github.com/postmanlabs/sails-mysql-transactions).  Check out https://github.com/balderdashy/waterline/pull/1310 for where we stand so far.

Specifically re: mysql, you might also want to check out the [ongoing work on the Waterline driver interface, particularly re: transactions](https://github.com/balderdashy/waterline/pull/1052#issuecomment-194572540).  Im pretty stoked about what's coming down the pipe, since it allows for finer-grained access to your app's database(s) without dropping all the way down to the level of native queries (a limitation thats blocked our progress somewhat up until recently).

**Comment by zeluis9** [comment]
Yup, I'm aware of all these stuff @mikermcneil. I'm following the framework's development closely. Only mentioned this bug because documentation has references to the select method, like @particlebanana pointed out. That said, can I do something to improve this? If so, how?

**Comment by raghunat** [comment]
@particlebanana @mikermcneil It seems projections are now officially supported in waterline 0.12, is development occurring for this feature now? (I am more interested in {select});

**Comment by particlebanana** [comment]
@raghunat @zeluis9 as of Waterline `0.12.0` projections are supported. If using a SQL adapter make sure you get the latest. This issue should be fixed up but keeping it open until it can be tested.
